apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: minimarket
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mranderson86/minimarket-backend-api
          ports:
            - containerPort: 9091
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: minimarket-configmap
                  key: mongo_url
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: 9091
          #  initialDelaySeconds: 5
          #  periodSeconds: 10
          #  timeoutSeconds: 5
          #  failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: minimarket
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091