namespace:
  name: minimarket

frontend:
  name: frontend
  replicas: 3
  image: mranderson86/minimarket-frontend
  tag: 1.0.0
  port: 9090
  nodePort: 30090

backend:
  name: backend
  replicas: 2
  image: mranderson86/minimarket-backend-api
  tag: 1.0.0
  port: 9091

consumer:
  name: consumer
  replicas: 2
  image: mranderson86/minimarket-backend-consumer
  tag: 1.0.0

mongo:
  name: mongo
  image: mongo
  tag: latest
  replicas: 1
  username: cm9vdA== #base64 for root
  password: cGFzczEyMzQ1 #base64 for pass12345
  storage_size: 1Gi
  port: 27017
  #if true, then it'll create a persistent volume, in the size of "storage_size" param,
  #otherwise, the PVC will be claimed from an existing PV
  #(meaning - if not true, then you must make sure there's an available PV before deploying mongo)
  create_pv: true

mongo_express:
  name: mongo-express
  image: mongo-express
  tag: latest
  replicas: 3
  username: YWRtaW4= #base64 for admin
  password: YWRtaW4xMjM= #base64 for admin123
  port: 8081
  nodePort: 30081

zookeeper:
  name: zookeeper
  image: zookeeper
  tag: latest
  replicas: 2
  port: 2181

kafka:
  name: kafka
  image: confluentinc/cp-kafka
  tag: 7.0.0
  replicas: 1 #will be 2 in the future, need to check bug
  port: 9092


