apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: minimarket
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: mranderson86/minimarket-backend-consumer
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: minimarket-configmap
                  key: mongo_url
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: minimarket-configmap
                  key: backend_url
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password