apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.consumer.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.consumer.name }}
spec:
  replicas: {{ .Values.consumer.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.consumer.name }}
  template:
    metadata:
      annotations:
        #This little guy will force redeployment in case of changes in the configmap,
        #thus will reload variables from the configmap
        #(example: adding new variable or changing the value of an existing variable in the configmap)
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: {{ .Values.consumer.name }}
    spec:
      containers:
        - name: {{ .Values.consumer.name }}
          image: {{ .Values.consumer.image }}:{{ .Values.consumer.tag }}
          env:
            - name: KAFKA_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.namespace.name }}-configmap
                  key: kafka_url
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.namespace.name }}-configmap
                  key: mongo_url
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongo.name }}-secret
                  key: username
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongo.name }}-secret
                  key: password