apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.backend.name }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      annotations:
        #This little guy will force redeployment in case of changes in the configmap,
        #thus will reload variables from the configmap
        #(example: adding new variable or changing the value of an existing variable in the configmap)
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: {{ .Values.backend.name }}
    spec:
      containers:
        - name: {{ .Values.backend.name }}
          image: {{ .Values.backend.image }}:{{ .Values.backend.tag }}
          ports:
            - containerPort: 9091
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.namespace.name }}-configmap
                  key: mongo_url
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongo.name }}-secret
                  key: username
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongo.name }}-secret
                  key: password
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: 9091
          #  initialDelaySeconds: 5
          #  periodSeconds: 10
          #  timeoutSeconds: 5
          #  failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}-service
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ .Values.backend.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend.port }}
      targetPort: 9091