apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.namespace.name }}-configmap
  namespace: {{ .Values.namespace.name }}
data:
  mongo_service_name: {{ .Values.mongo.name }}-service
  zookeeper_url: {{ .Values.zookeeper.name }}-service:{{ .Values.zookeeper.port }}
  mongo_url: {{ .Values.mongo.name }}-service:{{ .Values.mongo.port }}
  kafka_url: {{ .Values.kafka.name }}-service:{{ .Values.kafka.port }}
  backend_url: {{ .Values.backend.name }}-service:{{ .Values.backend.port }}
