kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv0001
  labels:
    type: local
spec:
  capacity:
    storage: {{ .Values.mongo.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data