{{- if .Values.mongo.create_pv }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv0001
  annotations:
    #This annotation is to keep the PV existing even after helm uninstall
    #In case other resources have PVC which are claimed from this PV
    "helm.sh/resource-policy": keep
  labels:
    type: local
spec:
  capacity:
    storage: {{ .Values.mongo.storage_size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
{{- end}}