apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.zookeeper.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: zookeeper
spec:
  replicas: {{ .Values.zookeeper.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.zookeeper.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.zookeeper.name }}
    spec:
      containers:
        - name: {{ .Values.zookeeper.name }}
          image: {{ .Values.zookeeper.image }}:{{ .Values.zookeeper.tag }}
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zookeeper.name }}-service
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ .Values.zookeeper.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.zookeeper.port }}
      targetPort: 2181